FROM wordpress:php8.2-apache

COPY wp-content/themes /var/www/html/wp-content/themes
COPY wp-content/plugins /var/www/html/wp-content/plugins
COPY wp-content/languages /var/www/html/wp-content/languages
COPY wp-content/index.php /var/www/html/wp-content/index.php

RUN chown -R www-data:www-data /var/www/html/wp-content
